//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossWordSolver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossWordSolver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s anderendaags
        ///&apos;s avonds
        ///&apos;s middags
        ///&apos;s nachts
        ///&apos;s ochtends
        ///&apos;s-Gravenhage
        ///&apos;s-Hertogenbosch
        ///06-nummer
        ///1 aprilgek
        ///1 aprilgrap
        ///1 aprilmop
        ///5 meiherdenking
        ///5 meiviering
        ///8 uurjournaal
        ///80-jarige
        ///A-biljet
        ///A-bom
        ///A-kant
        ///A-merk
        ///A-omroep
        ///A-status
        ///A4-formaat
        ///AAW-voorziening
        ///ABC-eilanden
        ///ABC-wapens
        ///ADHD
        ///ADHD-kind
        ///ADSL
        ///ADSL-aansluiting
        ///AMvB
        ///AOV
        ///AOV-uitkering
        ///AOW
        ///AOW&apos;er
        ///AOW-premie
        ///AOW-uitkering
        ///AROB
        ///ASFA
        ///ATB
        ///AWACS-vliegtuig
        ///AWBZ-premie
        ///AWW-premie
        ///AWW-uitkering
        ///Aarlen
        ///Aarlenaar
        ///Aarlens
        ///Aboriginal
        ///Aboriginals
        ///Aborigines
        ///Absur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NLOpenTaal_210G_basis_gekeurd {
            get {
                return ResourceManager.GetString("NLOpenTaal_210G_basis_gekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s Gravenvoeren
        ///&apos;s Gravenwezel
        ///&apos;s Herenelderen
        ///&apos;s-Graveland
        ///&apos;s-Gravendeel
        ///&apos;s-Gravenhaags
        ///&apos;s-Gravenhagenaar
        ///&apos;s-Gravenmoer
        ///&apos;s-Gravenzande
        ///&apos;s-Gravenzander
        ///&apos;s-Gravenzands
        ///A
        ///A-nummer
        ///A.D.
        ///A4
        ///ABN
        ///AD
        ///AIVD
        ///ANP
        ///ANSI
        ///ANVR
        ///ANW
        ///ANWB
        ///AOb
        ///API
        ///APV
        ///ASCII
        ///ASIC
        ///AWBZ
        ///Aa en Hunze
        ///Aad
        ///Aafje
        ///Aafke
        ///Aagje
        ///Aaigem
        ///Aaks
        ///Aalbeke
        ///Aalburg
        ///Aalsmeer
        ///Aalsmeerder
        ///Aalsmeers
        ///Aalst
        ///Aalstenaar
        ///Aalsters
        ///Aalten
        ///Aaltenaar
        ///Aaltens
        ///Aalter
        ///Aalteraar
        ///Aalters
        ///Aaltje
        ///Aantjes
        ///Aarle-Rixtel
        ///Aarschot
        ///Aarschots
        ///Aarschottenaar
        ///Aarsele
        ///Aart
        ///Aartrijke
        ///Aartselaa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NLOpenTaal_210G_basis_ongekeurd {
            get {
                return ResourceManager.GetString("NLOpenTaal_210G_basis_ongekeurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amsterdamse
        ///Arnhemse
        ///Eindhovense
        ///Estse
        ///Haarlemse
        ///Hasseltse
        ///Kanaaleilanden
        ///Limburgse
        ///Maasbreese
        ///Maastrichtse
        ///Nederlandse
        ///Noord-Brabantse
        ///Noord-Hollandse
        ///Overijsselse
        ///Rotterdamse
        ///Utrechtse
        ///Zuid-Hollandse
        ///adiabatische
        ///anticlimactische
        ///asymptotische
        ///axiologische
        ///axonometrische
        ///beoliede
        ///bionische
        ///blasfemistische
        ///blèrden
        ///blèrt
        ///brullend
        ///casuïstische
        ///cruises
        ///cryptografische
        ///cyclometrische
        ///derdeklassenreizigers
        ///diabetische
        ///gotische
        ///gsm&apos;etjes
        ///harmonische
        ///historische
        ///hoogenergetische
        ///hoogstaangeslagenen
        ///kerstmannetje
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NLOpenTaal_210G_flexievormen {
            get {
                return ResourceManager.GetString("NLOpenTaal_210G_flexievormen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julie
        ///aantelling
        ///aanvaart
        ///achterhoek
        ///afsluitdijk
        ///ars
        ///bei
        ///benthuizen
        ///brodden
        ///daggen
        ///dagvaart
        ///deen
        ///docentencorps
        ///dry
        ///eins
        ///engels
        ///erlangen
        ///fijt
        ///franse
        ///gebeid
        ///gebeiden
        ///gent
        ///gijl
        ///gijn
        ///gijnen
        ///goedkoopte
        ///handelswijze
        ///he
        ///heef
        ///ijslander
        ///jour
        ///kandidaatsstelling
        ///kiezerscorps
        ///kokschool
        ///kunne
        ///landschapschilder
        ///marc
        ///muite
        ///ngo
        ///ongelden
        ///openlucht
        ///peg
        ///perscorps
        ///puisje
        ///puisjes
        ///rechtsspraak
        ///rekenkamer
        ///rijn
        ///romein
        ///safe sex
        ///sent
        ///sext
        ///si
        ///ut
        ///veiligheidsraad
        ///verassen
        ///verassing
        ///wanner
        ///weit
        ///win-win
        ///wort
        ///xerox
        ///zijl
        ///zodiac
        ///aanspring
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NLOpenTaal_210G_verwarrend {
            get {
                return ResourceManager.GetString("NLOpenTaal_210G_verwarrend", resourceCulture);
            }
        }
    }
}
